do_none = 0
do_stand =  1  --
do_walk =  2  --
do_run =  3  --chay
do_jump =  4  --
do_skill =  5  --
do_magic =  6  --xai chieu
do_attack =  7  --tan cong
do_sit =  8  --ngoi
do_hurt = 9
do_death = 10
do_defense = 11
do_idle = 12
do_specialskill = 13
do_special1 = 14
do_special2 = 15
do_special3 = 16
do_special4 = 17
do_runattack = 18
do_manyattack = 19
do_jumpattack = 20
do_revive = 21
